# Generated by Django 6.0 on 2025-12-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="created_at",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Keyboard", "Keyboard"),
                    ("Mouse", "Mouse"),
                    ("Monitor", "Monitor"),
                    ("Accessory", "Accessory"),
                ],
                default="Keyboard",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
