# Generated by Django 6.0 on 2026-02-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_order_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
