# Generated by Django 5.2.11 on 2026-02-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Apparel', 'Apparel'), ('Footwear', 'Footwear'), ('Equipment', 'Equipment'), ('Accessories', 'Accessories')], default='Apparel', max_length=50),
        ),
    ]
